name: dynamicbind
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_kmp_llvm
  - appdirs=1.4.4=pyhd3eb1b0_0
  - asttokens=2.0.5=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boost=1.74.0=py310h7c3ba0c_5
  - boost-cpp=1.74.0=h75c5d50_8
  - brotli=1.0.9=h166bdaf_8
  - brotli-bin=1.0.9=h166bdaf_8
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.7.22=hbcca054_0
  - cairo=1.16.0=hb05425b_3
  - certifi=2023.7.22=pyhd8ed1ab_0
  - charset-normalizer=2.0.4=pyhd3eb1b0_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - cycler=0.11.0=pyhd8ed1ab_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.5.0=hcb278e6_1
  - ffmpeg=4.3=hf484d3e_0
  - fontconfig=2.14.2=h14ed4e7_0
  - freetype=2.12.1=h4a9f257_0
  - gettext=0.21.1=h27087fc_0
  - giflib=5.2.1=h5eee18b_3
  - glib=2.76.2=hfc55251_0
  - glib-tools=2.76.2=hfc55251_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - icu=70.1=h27087fc_0
  - intel-openmp=2023.1.0=hdb19cb5_46305
  - jbig=2.1=h7f98852_2003
  - jpeg=9e=h5eee18b_1
  - jupyter_client=8.1.0=py310h06a4308_0
  - jupyter_core=5.3.0=py310h06a4308_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.38=h1181459_1
  - lerc=3.0=h295c915_0
  - libbrotlicommon=1.0.9=h166bdaf_8
  - libbrotlidec=1.0.9=h166bdaf_8
  - libbrotlienc=1.0.9=h166bdaf_8
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.6.1.9=0
  - libcurand=10.3.2.106=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libdeflate=1.8=h7f8727e_5
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h6a678d5_6
  - libgcc-ng=12.2.0=h65d4601_19
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libglib=2.76.2=hebfc3b9_0
  - libiconv=1.17=h166bdaf_0
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.7.4.75=0
  - libnsl=2.0.0=h7f98852_0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.39=h5eee18b_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.42.0=h2797004_0
  - libstdcxx-ng=12.2.0=h46fd767_19
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.3.0=h6f004c6_2
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp=1.2.4=h11a3e52_1
  - libwebp-base=1.2.4=h5eee18b_1
  - libxcb=1.15=h0b41bf4_0
  - libzlib=1.2.13=h166bdaf_4
  - llvm-openmp=16.0.3=h4dfa4b3_0
  - lz4-c=1.9.4=h6a678d5_0
  - matplotlib-base=3.7.1=py310he60537e_0
  - mkl=2023.1.0=h6d00ec8_46342
  - mkl_fft=1.3.6=py310h1128e8f_1
  - mkl_random=1.2.2=py310h1128e8f_1
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - ncurses=6.4=h6a678d5_0
  - nettle=3.7.3=hbbd107a_1
  - numpy-base=1.24.3=py310hb5e798b_1
  - openh264=2.1.1=h4ff587b_0
  - openssl=3.1.2=hd590300_0
  - packaging=23.1=pyhd8ed1ab_0
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre2=10.40=hc3806b6_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pixman=0.40.0=h36c2ea0_0
  - pooch=1.4.0=pyhd3eb1b0_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pycparser=2.21=pyhd3eb1b0_0
  - pyg=2.3.0=py310_torch_2.0.0_cu117
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - python=3.10.12=hd12c33a_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python-tzdata=2023.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytorch=2.0.1=py3.10_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - pytz=2023.3=pyhd8ed1ab_0
  - rdkit=2022.03.5=py310h1c297d8_0
  - readline=8.2=h5eee18b_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.41.2=h5eee18b_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tbb=2021.8.0=hdb19cb5_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.12=h1ccaba5_0
  - torchtriton=2.0.0=py310
  - typing_extensions=4.5.0=py310h06a4308_0
  - tzdata=2023c=h04d1e81_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.2.6=h166bdaf_0
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zlib=1.2.13=h166bdaf_4
  - zstd=1.5.2=hfc55251_7
  - pip:
    - biopython==1.78
    - brotlipy==0.7.0
    - cffi==1.15.1
    - comm==0.1.2
    - contourpy==1.0.7
    - cryptography==38.0.4
    - debugpy==1.5.1
    - e3nn==0.5.1
    - fair-esm==2.0.0
    - filelock==3.9.0
    - fonttools==4.39.3
    - gmpy2==2.1.2
    - greenlet==2.0.2
    - idna==3.4
    - ipykernel==6.19.2
    - ipython==8.12.0
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.1.1
    - jupyter-client==8.1.0
    - jupyter-core==5.3.0
    - kiwisolver==1.4.4
    - markupsafe==2.1.1
    - matplotlib==3.7.1
    - matplotlib-inline==0.1.6
    - mkl-fft==1.3.6
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - mpmath==1.2.1
    - nest-asyncio==1.5.6
    - networkx==2.8.4
    - numpy==1.24.3
    - opt-einsum==3.3.0
    - opt-einsum-fx==0.1.4
    - pandas==2.0.1
    - pillow==9.4.0
    - pip==23.0.1
    - platformdirs==2.5.2
    - prompt-toolkit==3.0.36
    - psutil==5.9.0
    - https://data.pyg.org/whl/torch-2.0.0%2Bcu117/pyg_lib-0.2.0%2Bpt20cu117-cp310-cp310-linux_x86_64.whl
    - pygments==2.15.1
    - pyopenssl==23.0.0
    - pysocks==1.7.1
    - pyyaml==6.0
    - pyzmq==25.0.2
    - reportlab==3.6.13
    - requests==2.29.0
    - scikit-learn==1.2.2
    - scipy==1.10.1
    - setuptools==66.0.0
    - spyrmsd==0.5.2
    - sqlalchemy==1.4.46
    - sympy==1.11.1
    - torch==2.0.1
    - https://data.pyg.org/whl/torch-2.0.0%2Bcu117/torch_cluster-1.6.1%2Bpt20cu117-cp310-cp310-linux_x86_64.whl
    - torch-geometric==2.3.0
    - https://data.pyg.org/whl/torch-2.0.0%2Bcu117/torch_scatter-2.1.1%2Bpt20cu117-cp310-cp310-linux_x86_64.whl
    - https://data.pyg.org/whl/torch-2.0.0%2Bcu117/torch_sparse-0.6.17%2Bpt20cu117-cp310-cp310-linux_x86_64.whl
    - https://data.pyg.org/whl/torch-2.0.0%2Bcu117/torch_spline_conv-1.2.2%2Bpt20cu117-cp310-cp310-linux_x86_64.whl
    - torchaudio==2.0.2
    - torchvision==0.15.2
    - tornado==6.2
    - tqdm==4.65.0
    - traitlets==5.7.1
    - triton==2.0.0
    - typing-extensions==4.5.0
    - unicodedata2==15.0.0
    - urllib3==1.26.15
    - wheel==0.38.4
prefix: /gxr/luwei/anaconda3/envs/dynamicbind
